apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-sample-app
  template:
    metadata:
      labels:
        app: java-sample-app
    spec:
      containers:
        - name: java-sample-app
          image: PLACEHOLDER_IMAGE
          ports:
            - containerPort: 8080
          resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: java-sample-service
spec:
  selector:
    app: java-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
